const KEY="vmc_demo_user", CARDS="vmc_demo_cards";
function register(){const n=document.getElementById("name").value.trim(),e=document.getElementById("email").value.trim(),p=document.getElementById("pass").value;if(!n||!e||!p)return alert("নাম, ইমেইল ও পাসওয়ার্ড দিন।");localStorage.setItem(KEY,JSON.stringify({n,e}));showApp()}
function showApp(){document.getElementById("auth").classList.add("hidden");document.getElementById("app").classList.remove("hidden");render()}
function logout(){localStorage.removeItem(KEY);location.reload()}
function cards(){return JSON.parse(localStorage.getItem(CARDS)||"[]")}
function save(a){localStorage.setItem(CARDS,JSON.stringify(a))}
function createCard(){let customer=document.getElementById("customer").value.trim(),email=document.getElementById("customerEmail").value.trim(),nick=document.getElementById("nickname").value.trim(),theme=document.getElementById("theme").value;if(!customer||!email)return alert("Customer name ও email দিন।");let a=cards(), id=Date.now();a.unshift({id,customer,email,nick:nick||"My Card",theme,status:"Active",number:"5555 •••• •••• "+String(id).slice(-4),expiry:"12/30"});save(a);document.getElementById("customer").value="";document.getElementById("customerEmail").value="";document.getElementById("nickname").value="";render()}
function del(id){save(cards().filter(x=>x.id!==id));render()}
function render(){let a=cards();document.getElementById("total").textContent=a.length;document.getElementById("active").textContent=a.filter(x=>x.status==="Active").length;document.getElementById("pending").textContent=a.filter(x=>x.status==="Pending").length;let out=a.length?a.map(x=>`<div class="card"><div class="mc ${x.theme.toLowerCase()}"><b>VIRTUAL MASTERCARD</b><div class="num">${x.number}</div><small>${x.customer} &nbsp; • &nbsp; ${x.expiry}</small></div><div class="info"><b>${x.nick}</b><p>${x.customer}<br>${x.email}</p><span class="badge">${x.status}</span><br><button style="margin-top:10px;background:#dc2626" onclick="del(${x.id})">Delete Demo Card</button></div></div>`).join(""):"<p>এখনও কোনো card তৈরি হয়নি।</p>";document.getElementById("cards").innerHTML=out}
if(localStorage.getItem(KEY))showApp();